export const NOTIFICATION = {
    SET_MESSAGE: 'SET_MESSAGE'
};

export const AUTH = {
    SEND_LOGIN_DATA_REQUEST: 'SEND_LOGIN_DATA_REQUEST',
    SEND_LOGIN_DATA_SUCCESS: 'SEND_LOGIN_DATA_SUCCESS',
    SEND_LOGIN_DATA_FAILURE: 'SEND_LOGIN_DATA_FAILURE',
};
