export const NOTIFICATION = {
    SET_MESSAGE: 'SET_MESSAGE'
};

export const AUTH = {
    SEND_LOGIN_DATA_REQUEST: 'SEND_LOGIN_DATA_REQUEST',
    SEND_LOGIN_DATA_SUCCESS: 'SEND_LOGIN_DATA_SUCCESS',
    SEND_LOGIN_DATA_FAILURE: 'SEND_LOGIN_DATA_FAILURE',
};

export const GET_TREE = {
    SGET_TREE_REQUEST: 'GET_TREE_REQUEST',
    GET_TREE_SUCCESS: 'GET_TREE_SUCCESS',
    GET_TREE_FAILURE: 'GET_TREE_FAILURE',
};
